name: Tests
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: clojure:temurin-17-tools-deps-1.11.1.1165
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            /root/.m2
            /root/.gitlibs
          key: test-${{ hashFiles('deps.edn') }}
          restore-keys: test-
      - run: clojure -X:test
